### ISSUE TITLE
Improving performance of puzzle generator

### ISSUE THREAD

**Issue by philshem** [philshem/open-spelling-bee#1]
It's quite slow, at about 100 puzzles in 12 hours on my MacBook Pro (2015), although the filters for quality games are relatively narrow.

The code [generate_puzzles.py](https://github.com/philshem/open-spelling-bee/blob/master/generate_puzzles.py) and function `make_puzzles()` has multi-threading over the word_list ([see code](https://github.com/philshem/open-spelling-bee/blob/8df2447b2aed0f49fd2ed9bb60f507e52b6fd013/generate_puzzles.py#L79-L84)), instead of multiple arrays of letter combinations. Since the word_list is always constant, it's probably better to create chunks of letter arrays and do multi-threading over them.

**Comment by tcjr** [comment]
Hi,

This is a cool project.

I think a good strategy to speed it up is to limit the combinations of letters to try.  That is, instead of choosing 7 random letters, be smarter about the original letters to try.  

Since we know every set of valid letters must have at least one pangram, I think it makes sense to start there.  Start with 7+ letter words in the dictionary that have exactly 7 unique letters.  The first few such words in the dictionary are:

AARDWOLF
AASVOGEL
AASVOGELS
ABALONES
ABAMPERES
ABANDONER
ABANDONING
ABASEDLY
ABASEMENT
ABASEMENTS
…

Removing duplicate letters and sorting them, you get a list like this:

ADFLORW
AEGLOSV
AEGLOSV
ABELNOS
ABEMPRS
ABDENOR
ABDGINO
ABDELSY
ABEMNST
ABEMNST
…

Then, removing duplicates from the list, you get:

ADFLORW
AEGLOSV
ABELNOS
ABEMPRS
ABDENOR
ABDGINO
ABDELSY
ABEMNST
…

This list is essentially a pool of all the valid pangramable letter groups.  There are 16,475 of these.  You can use permutations of each of these letter groups to try as candidates.  Consider the first one, ADFLORW.  You have 7 significant permutations of this, meaning: 7 combinations with a different letter first.  Interestingly, only one of these, WADFLOR, is a valid puzzle (using the defaults).

letters|word_count|total_score|pangram_count
-------|-----------|-----------|-------------
ADFLORW|72|150|1
DAFLORW|55|107|1
FADLORW|52|104|1
LADFORW|60|116|1
OADFLRW|81|156|1
RADFLOW|56|110|1
WADFLOR|38|85|1

In general, this strategy produces letters that have too many words and too high of scores, instead of too few or too low.  Case in point, the second pool entry from above produces zero valid puzzles:

letters|word_count|total_score|pangram_count
---|---|---|---
AEGLOSV|204|499|3
EAGLOSV|227|568|3
GAELOSV|143|370|3
LAEGOSV|245|613|3
OAEGLSV|121|277|3
SAEGLOV|251|630|3
VAEGLOS|111|309|3

Despite this "overshooting", I still think this is a valid technique since it narrows the universe of possible candidates to 16,475 x 7, or 115,325.  That is a very manageable size.

To try this out, I updated the puzzle generator to do roughly what I described above.  Unfortunately, I don't know Python, so it's not pretty.

**Comment by philshem** [comment]
Hi @tcjr - glad you like the project. The solution is very clever. Thanks!
